name: Release

on:
  push:
    tags: [v*]

permissions:
  contents: write

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
          cache: true

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Build
        env:
          GOOS: windows
          CGO_ENABLED: 0
        run: |
          bun x esbuild src/index.ts --bundle --format=iife --platform=browser --outfile=vcc-auto-translate.js
          go build -trimpath -ldflags "-s -w" -o build/ ./...
          cp vcc-auto-translate.js build/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
