name: Release

on:
  push:
    tags: [v*]
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Install esbuild
        run: curl -fsSL https://esbuild.github.io/dl/latest | sh

      - name: Build
        run: make

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/*
